"""Conteúdo editorial original em português; usado no site e na documentação."""
MODULES = []
def m(id, title, group, summary, refs, body, recall, answer):
    MODULES.append(dict(id=id,title=title,group=group,summary=summary,refs=refs,body=body,recall=recall,answer=answer))

SOURCES = {
 'iso9283': ('ISO — critérios de desempenho e métodos de ensaio, ISO 9283:1998', 'https://committee.iso.org/cms/live/live/en/sites/isoorg/contents/data/standard/02/22/22244.html?browse=ics'),
 'graus': ('Modern Robotics — graus de liberdade', 'https://modernrobotics.northwestern.edu/nu-gm-book-resource/2-2-degrees-of-freedom-of-a-robot/'),
 'direta': ('Modern Robotics — cinemática direta', 'https://modernrobotics.northwestern.edu/chapters/chapter4/'),
 'inversa': ('Modern Robotics — cinemática inversa', 'https://modernrobotics.northwestern.edu/chapters/chapter6/'),
 'singular': ('Modern Robotics — singularidades', 'https://modernrobotics.northwestern.edu/nu-gm-book-resource/5-3-singularities/'),
 'ros': ('Open Robotics — actions no ROS 2', 'https://design.ros2.org/articles/actions.html'),
 'pwm': ('Arduino — referência oficial de analogWrite', 'https://github.com/arduino/reference-en/blob/master/Language/Functions/Analog%20IO/analogWrite.adoc'),
 'visao': ('OpenCV — limiarização de imagens', 'https://docs.opencv.org/4.10.0/d7/d4d/tutorial_py_thresholding.html'),
 'seguranca': ('OSHA — sistemas robóticos industriais e segurança', 'https://www.osha.gov/otm/section-4-safety-hazards/chapter-4'),
 'historia': ('Computer History Museum — AI & Robotics', 'https://www.computerhistory.org/timeline/ai-robotics/'),
 'babbage': ('Science Museum — os projetos de Babbage', 'https://blog.sciencemuseum.org.uk/iconic-babbage-drawings-to-go-on-display/'),
 'dartmouth': ('Dartmouth — história da inteligência artificial', 'https://ai.dartmouth.edu/our-story'),
 'shakey': ('DARPA — Shakey the Robot', 'https://www.darpa.mil/about/innovation-timeline/shakey-the-robot'),
 'nasa': ('NASA — robótica e exploração', 'https://www.nasa.gov/robotics/'),
}
# A, I, C, M: páginas físicas do PDF, contadas desde a capa.
FILES = {'A':'Apostila_wm.pdf','I':'Aula02_14_08_2026.pdf','C':'Aula03_21_08_wm.pdf','M':'Aula06_11_09_2026_wm.pdf'}

m('fundamentos','O que é um robô?','Fundamentos','Entenda automação, autonomia e a relação entre mecânica, eletrônica e software.', [('A','2'),('I','11-14')], '''
<h2>Comece pelo ciclo completo</h2><p>Um robô reúne um corpo mecânico, meios de agir, um controlador e, conforme a aplicação, sensores. O controlador transforma comandos e medições em ações físicas. Pense em uma garra que pega uma peça: o programa escolhe o movimento, o driver entrega energia ao motor, a transmissão move a junta e o sensor informa o resultado. Cada parte resolve uma etapa diferente.</p>
<p>A robótica industrial estuda especialmente manipuladores reprogramáveis usados para movimentar peças e ferramentas. Robótica em sentido amplo inclui também veículos móveis, dispositivos médicos e sistemas de exploração. Forma humana não é requisito; braços industriais frequentemente têm uma aparência bastante diferente de uma pessoa.</p>
<h2>Automático, autônomo e teleoperado</h2><p><strong>Automático</strong> executa uma sequência sem intervenção contínua. <strong>Autônomo</strong> toma decisões dentro de objetivos e limites definidos, com base no ambiente. <strong>Teleoperado</strong> recebe decisões de um operador distante. As categorias podem coexistir: um veículo teleoperado pode controlar automaticamente a velocidade de suas rodas.</p><p>Uma máquina dedicada pode executar uma operação fixa. A reprogramabilidade permite mudar uma sequência de movimentos, mas não remove limites físicos de alcance, carga, ferramentas e segurança. IA pode ajudar em tarefas de percepção ou decisão; um robô não precisa de aprendizado de máquina para funcionar.</p>
<h2>Os três pilares e seus pré-requisitos</h2><ul><li>Mecânica: força, torque, materiais, juntas e transmissões.</li><li>Eletrônica: tensão, corrente, sensores, alimentação e drivers.</li><li>Computação e controle: algoritmos, comunicação, realimentação e planejamento.</li></ul>
<div class="worked"><h3>Exemplo: célula de paletização</h3><p>Uma esteira apresenta caixas. O sensor detecta a chegada, o controlador seleciona a posição no palete e o braço transporta a caixa com uma garra. Isso pode ser um sistema automático com posições ensinadas. Para lidar com caixas em posições imprevisíveis, acrescentam-se percepção e decisões de trajetória.</p></div>
<h2>Como responder na prova</h2><p>Descreva função e fluxo de informações. Evite definir robô apenas como “máquina inteligente”: a definição fica vaga e exclui manipuladores industriais que seguem programas determinísticos.</p>''','Todo sistema automático é autônomo?','Não. Executar uma sequência fixa automaticamente não implica decidir como agir diante de mudanças no ambiente.')

m('historia','História da robótica','Fundamentos','Ligue os marcos históricos às capacidades que eles introduziram.', [('I','15-68'),'historia','shakey'], '''
<h2>Uma história de capacidades</h2><p>A aula percorre autômatos antigos, mecanismos programáveis, ficção, teleoperação, robôs industriais, máquinas móveis e humanoides. Estude o que mudou em cada etapa: fonte de energia, armazenamento de instruções, sensores, controle ou autonomia. Decorar nomes isolados é menos útil do que conseguir explicar essa evolução.</p>
<div class="table-wrap"><table><tr><th>Etapa apresentada</th><th>O que você precisa compreender</th></tr><tr><td>Ctesíbio e mecanismos antigos</td><td>Água, ar e mecanismos realizam ações sem computadores eletrônicos.</td></tr><tr><td>Leonardo e Jaquet-Droz</td><td>Movimentos mecânicos podem reproduzir gestos e sequências; reconstrução histórica não equivale a uma máquina autônoma moderna.</td></tr><tr><td>Jacquard</td><td>Cartões perfurados representam instruções externas ao mecanismo.</td></tr><tr><td>Telemanipuladores</td><td>Permitem atuar a distância, incluindo ambientes com materiais radioativos.</td></tr><tr><td>Devol, Engelberger e Unimate</td><td>Reprogramação e manipulação entram no ambiente industrial.</td></tr><tr><td>Shakey</td><td>Percepção e planejamento passam a orientar um robô móvel.</td></tr><tr><td>PUMA, SCARA e paralelos</td><td>Arquiteturas são adaptadas a tarefas de montagem e manipulação.</td></tr><tr><td>Sojourner, Aibo, ASIMO, Qrio e robôs de serviço</td><td>Exploração, entretenimento, locomoção e tarefas domésticas ampliam as aplicações.</td></tr></table></div>
<h2>Datas com contexto</h2><p>A linha do tempo do Computer History Museum registra a instalação industrial do Unimate em <strong>1961</strong>. O slide da aula menciona 1962; mantenha essa divergência visível ao estudar. Shakey foi um projeto desenvolvido ao longo de anos, associado ao apoio iniciado em 1966, e não uma invenção feita em um único dia. A aula usa 1968 como marco didático.</p>
<h2>Reatividade também é inteligência de comportamento</h2><p>As tartarugas de Grey Walter, apresentadas em 1949–1950 no material, ajudam a entender como sensores simples e regras de ação produzem comportamento observável. O ponto importante é o acoplamento entre perceber e mover-se. Mais sensores ou processadores não garantem, sozinhos, uma arquitetura melhor.</p>
<div class="worked"><h3>Resposta comparativa</h3><p>Um autômato executa movimentos previstos pelo mecanismo. Um telemanipulador depende das decisões humanas. Um robô planejador usa um modelo para escolher ações. Compare a origem das decisões, em vez de ordenar todos como “menos” ou “mais” robóticos.</p></div>''','Por que Shakey é um marco diferente de um braço industrial que repete posições?','Porque combina percepção do ambiente e planejamento para orientar a navegação, enquanto a repetição industrial pode usar posições previamente ensinadas.')

m('computacao-ficcao','Computação, autômatos e ficção','Fundamentos','Entenda cartões perfurados, Babbage, Asimov e o nascimento da IA.', [('I','20-33'),('I','42'),'babbage','dartmouth'], '''
<h2>Programar antes da eletrônica</h2><p>Uma sequência de instruções não precisa estar em um chip. Cames, engrenagens e cartões perfurados podem determinar a ordem de ações. Nos teares associados a Jacquard, o padrão de perfurações seleciona operações de tecelagem. Alterar as instruções muda o padrão produzido sem reconstruir toda a máquina. Essa separação entre mecanismo e instrução antecipa uma ideia central da computação.</p>
<h2>Babbage: duas máquinas diferentes</h2><p>A <strong>máquina diferencial</strong> foi concebida para calcular tabelas numéricas por diferenças. A <strong>máquina analítica</strong> é o projeto mais próximo da noção de computador programável de propósito geral. O slide 25 mistura esses papéis ao atribuir propósito geral à máquina diferencial; o Science Museum distingue os dois projetos. Não confunda cálculo automático de uma classe de problemas com execução de programas variados.</p>
<h2>R.U.R., Metropolis e Asimov</h2><p>A aula apresenta R.U.R. de Karel Čapek como origem da palavra robô e destaca a relação de “robota” com trabalho compulsório. Os personagens dessa peça não são simplesmente braços metálicos industriais. Metropolis e os robôs de filmes servem para discutir como a cultura imagina máquinas, trabalhadores e poder. São referências culturais, não especificações de engenharia.</p>
<p>As três leis de Asimov são regras narrativas sobre proteger humanos, obedecer a ordens compatíveis com essa proteção e preservar o próprio robô quando isso não conflita com as anteriores. Elas exploram dilemas e ambiguidades. Uma célula industrial real depende de análise de riscos, proteções, funções de parada e procedimentos verificáveis; não de uma frase ética instalada no programa.</p>
<h2>Dartmouth e inteligência artificial</h2><p>O termo inteligência artificial aparece na proposta de 1955 para o encontro realizado em Dartmouth em 1956. A ideia era investigar se aspectos da inteligência poderiam ser descritos e simulados por máquinas. Isso ajuda a separar o campo científico da aparência humana de um robô.</p>
<div class="worked"><h3>Conexão com programação atual</h3><p>Um cartão perfurado, um programa em C e uma sequência de pontos de um manipulador são formas diferentes de representar instruções. O suporte muda; continuam necessárias regras de interpretação e um mecanismo capaz de executar a instrução.</p></div>''','Qual projeto de Babbage é associado a propósito geral?','A máquina analítica. A máquina diferencial foi concebida para cálculo de tabelas por diferenças.')

m('paradigmas','Paradigmas e arquitetura de decisões','Fundamentos','Compare percepção–ação, planejamento e arquitetura híbrida.', [('C','3-5'),('I','59')], '''
<h2>Três maneiras de decidir</h2><p>No paradigma <strong>reativo</strong>, medições acionam comportamentos diretamente: detectar obstáculo → diminuir velocidade. O sistema responde rapidamente, mas regras locais podem entrar em conflito ou prender o robô em situações difíceis. No paradigma <strong>deliberativo</strong>, o robô percebe, constrói ou atualiza um modelo, planeja e então executa. Isso favorece objetivos de longo prazo, mas depende da qualidade do modelo e do tempo disponível.</p>
<p>Uma arquitetura <strong>híbrida</strong> combina planejamento global com comportamentos locais. Um planejador define o caminho até uma sala e um controlador local ajusta o movimento diante de uma pessoa. O projeto precisa decidir prioridades: uma ação de parada pode prevalecer sobre a rota planejada.</p>
<h2>Os exemplos específicos da aula</h2><ul><li>PINÓQUIO: dois motores CC, contato e luz, processador 80486, C e percepção–ação.</li><li>SOFIA: três motores de passo, contato, luz e infravermelho, 80486, C e percepção–planejamento–ação.</li><li>ASIMOV: motores CC com encoder, sonar, câmera, infravermelho e contato; vários processadores; paradigma híbrido e múltiplas linguagens.</li></ul><p>Essas especificações são exemplos históricos do slide, não recomendações atuais de compra. ASIMOV é o nome do robô citado; não confunda com o humanoide ASIMO da Honda.</p>
<h2>Subsumption e prioridades</h2><p>A aula histórica apresenta a arquitetura de subsunção associada a Brooks. A ideia didática é organizar comportamentos em camadas que podem suprimir ou inibir outros comportamentos. É possível obter uma ação útil sem produzir primeiro uma descrição completa do mundo. Isso não significa que toda representação ou planejamento seja sempre desnecessário.</p>
<div class="worked"><h3>Um robô de entrega</h3><p>“Se distância &lt; 0,3 m, pare” é uma regra reativa. “Escolha o corredor com menor custo” é deliberação. “Siga a rota, mas reduza a velocidade diante de pessoas” combina as duas. Justifique a arquitetura pela tarefa e pelo ambiente.</p></div>''','Que parte de uma arquitetura híbrida deve responder a um obstáculo inesperado próximo?','A camada local de percepção e reação/controle, integrada às prioridades de segurança; o plano global pode ser atualizado depois.')

m('matematica','Matemática e física essenciais','Bases de apoio','Revise unidades, trigonometria, vetores, energia e torque antes das contas.', [('A','25-26'),('M','28-35')], '''
<h2>Unidades e conversões</h2><p>Comprimento entra em metros ou milímetros, massa em quilogramas, tempo em segundos, força em newtons e torque em newton-metro. Não some grandezas incompatíveis. Uma posição angular em graus precisa ser convertida para radianos antes de usar fórmulas como s = rθ. Uma rotação completa corresponde a 360° = 2π rad.</p><div class="formula">θ(rad) = θ(graus) × π/180<br>ω(rad/s) = rpm × 2π/60<br>F = ma   |   Peso = mg   |   τ = rF sen(α)<br>P_elétrica = VI   |   P_mecânica = τω   |   E = Pt</div>
<p>O ângulo α é o ângulo entre o vetor posição do ponto de aplicação e a força. A expressão τ = rF vale para uma força perpendicular ao braço de alavanca. Massa de 2 kg não é força de 2 N: o peso é aproximadamente 19,62 N na superfície terrestre, usando g = 9,81 m/s².</p>
<h2>Trigonometria como projeção</h2><p>Um elo de comprimento L formando θ com o eixo x tem projeções x = L cos θ e y = L sen θ. Seno e cosseno não são comprimentos: são fatores sem unidade. Em 0°, o elo aponta totalmente para x; em 90°, aponta para y. Para dois elos, some as projeções, respeitando se o ângulo é relativo ao elo anterior.</p>
<h2>Vetores e matrizes</h2><p>Um vetor representa componentes em um referencial. Uma matriz pode transformar essas componentes ou relacionar taxas de variação. A multiplicação de matrizes geralmente depende da ordem: girar e depois transladar pode produzir resultado diferente de transladar e depois girar. Na robótica, sempre declare o referencial.</p>
<div class="worked"><h3>Torque estático de uma carga</h3><p>Uma massa de 2 kg a 0,4 m do eixo, com o braço horizontal, exige τ = 2 × 9,81 × 0,4 = <strong>7,848 N·m</strong> só para equilibrar seu peso. Ainda faltam o peso do braço, aceleração, atrito, perdas e margens de projeto. Uma conta estática é um ponto de partida, não o dimensionamento completo.</p></div>
<h2>Derivada e integral sem mistério</h2><p>A derivada indica o quanto uma grandeza muda por unidade de tempo: velocidade é a taxa de mudança da posição. A integral acumula contribuições: somar velocidade ao longo do tempo produz deslocamento. No PID, a integral acumula erro e a derivada indica como o erro está variando.</p>''','Um motor a 60 rpm gira a quantos rad/s?','A uma volta por segundo, ou 2π rad/s, aproximadamente 6,283 rad/s.')

m('estrutura','Estrutura mecânica e anatomia','Mecânica','Identifique base, elos, juntas, punho e efetuador.', [('A','3-8'),('C','13-20'),('M','2')], '''
<h2>Da base à ferramenta</h2><p>A <strong>base</strong> sustenta o manipulador e define uma referência. Os <strong>elos</strong> são os corpos que conectam articulações. As <strong>juntas</strong> permitem movimento relativo entre os elos. O <strong>punho</strong> concentra movimentos próximos da ferramenta, usados sobretudo para orientar o efetuador. O <strong>órgão terminal</strong>, efetuador ou end-effector executa a tarefa: agarrar, soldar, pintar ou medir.</p><p>Em uma junta, o elo de entrada é o mais próximo da base e o elo de saída é o mais próximo da ferramenta. Carenagens escondem eixos e mecanismos; reconhecer uma junta exige analisar o movimento, não apenas o formato externo.</p>
<h2>Cadeia aberta, fechada e parcialmente fechada</h2><p>Em uma cadeia serial aberta existe um caminho sequencial entre base e ferramenta. Em uma cadeia fechada, há um laço mecânico. Manipuladores paralelos conectam base e plataforma por várias cadeias. Uma cadeia parcialmente fechada pode empregar mecanismos auxiliares para transmitir movimento a uma junta, sem tornar todo o robô uma plataforma paralela.</p>
<p>Juntas passivas também se movem, embora não tenham motor próprio. Contar todos os motores ou todas as articulações visíveis não resolve automaticamente o número de graus de liberdade; vínculos mecânicos podem acoplar movimentos.</p>
<h2>Rigidez, massa e vibração</h2><p>Rigidez é a oposição à deformação. Uma estrutura leve reduz a inércia, mas precisa sustentar cargas sem flexão excessiva. Colocar motores pesados perto da base e transmitir o movimento pode reduzir a massa móvel. Por outro lado, transmissões acrescentam elasticidade, perdas ou folgas.</p>
<div class="worked"><h3>Diagrama funcional de uma junta</h3><p>Comando → driver → motor → redutor → junta → elo. Um encoder pode medir o motor ou a própria junta. Se medir antes do redutor, parte da folga ou deformação posterior pode não aparecer diretamente na medição. O local do sensor muda o que o controlador sabe.</p></div>''','Qual é a diferença entre punho e órgão terminal?','O punho orienta a extremidade por suas juntas; o órgão terminal é a garra ou ferramenta que realiza a tarefa.')

m('juntas','Juntas e graus de liberdade','Mecânica','Conte movimentos independentes e traduza as notações dos materiais.', [('A','4-8'),('C','17-20'),('M','14-19'),'graus'], '''
<h2>O que significa um grau de liberdade?</h2><p>Um grau de liberdade (GL, GD ou DOF) é uma coordenada independente necessária para descrever a configuração. Uma junta rotacional ideal permite um ângulo; uma prismática permite um deslocamento. Em uma cadeia aberta sem acoplamentos, some os graus de liberdade das juntas. Em mecanismos com laços, os vínculos impõem restrições e essa soma pode superestimar a mobilidade.</p>
<table><tr><th>Junta ideal</th><th>Movimento</th><th>GL</th></tr><tr><td>Rotacional/revoluta</td><td>Rotação em um eixo</td><td>1</td></tr><tr><td>Prismática</td><td>Translação em um eixo</td><td>1</td></tr><tr><td>Cilíndrica</td><td>Rotação e translação independentes no mesmo eixo</td><td>2</td></tr><tr><td>Esférica</td><td>Orientação em torno de três eixos</td><td>3</td></tr><tr><td>Helicoidal/fuso</td><td>Rotação ligada à translação pelo passo</td><td>1</td></tr><tr><td>Planar geral</td><td>Duas translações e uma rotação no plano</td><td>3</td></tr></table>
<div class="notice warning"><strong>Uma convenção específica da apostila</strong><p>A apostila chama de “planar” uma combinação de duas juntas prismáticas, com 2 GL. Uma junta planar geral na mecânica de corpos rígidos também permite girar no plano, totalizando 3 GL. Declare qual modelo está usando; não apague essa diferença.</p></div>
<h2>R/P e L/T/R/V</h2><p>Na aula de manipuladores, R representa uma junta rotacional e P uma prismática. A apostila usa L para linear e distingue T (torcional), R (rotacional) e V (revolvente) pela direção dos elos em relação ao eixo. T, R e V são todas juntas de rotação com 1 GL. Assim, as letras dependem da convenção, e uma ilustração pode admitir nomes diferentes se os elos forem representados de outra forma.</p>
<h2>Posição, orientação e redundância</h2><p>Um corpo livre no espaço tem três coordenadas de posição e três de orientação. Uma tarefa planar pode exigir somente x, y e um ângulo. Um braço de 7 GL pode ser redundante para uma tarefa de pose espacial com seis variáveis; a redundância é relativa à tarefa. Sete GL não tornam todo ponto alcançável nem eliminam singularidades.</p>
<div class="worked"><h3>Conte corretamente</h3><p>Duas juntas R e uma P independentes dão 3 GL. Um fuso que gira 360° e avança um passo não dá 2 GL: o avanço é determinado pela rotação, então existe apenas uma coordenada independente.</p></div>''','Por que uma junta de parafuso tem um GL?','Porque rotação e translação são vinculadas pelo passo do parafuso; não podem ser escolhidas de forma independente.')

m('configuracoes','Tipos de manipuladores','Mecânica','Compare cartesiano, cilíndrico, polar, SCARA, articulado e paralelo.', [('A','9-15'),('M','20-26'),('M','36-38')], '''
<h2>A arquitetura segue a tarefa</h2><p>Classificar um braço significa observar os movimentos principais e sua geometria. As letras abaixo usam R/P e descrevem o posicionamento principal; juntas de punho e ferramenta podem acrescentar eixos. Não trate RRP como identificação suficiente: orientação dos eixos distingue polar e SCARA.</p>
<div class="table-wrap"><table><tr><th>Tipo</th><th>Estrutura típica</th><th>Volume aproximado / uso</th><th>Limitação a analisar</th></tr><tr><td>Cartesiano / pórtico</td><td>PPP, eixos ortogonais</td><td>Paralelepípedo; transporte, CNC, paletização</td><td>Estrutura e área de instalação</td></tr><tr><td>Cilíndrico</td><td>RPP</td><td>Setor cilíndrico; alcance radial</td><td>Região próxima do eixo e limites de curso</td></tr><tr><td>Polar / esférico</td><td>RRP</td><td>Setor de casca esférica</td><td>Limites angulares e alcance mínimo</td></tr><tr><td>SCARA</td><td>RR no plano + P vertical; frequentemente mais um R</td><td>Montagem e inserção com complacência seletiva</td><td>Orientações e alcance restritos</td></tr><tr><td>Articulado / antropomórfico</td><td>RRR no braço; punho adicional</td><td>Soldagem, manipulação em espaço complexo</td><td>Cinemática, singularidades e rigidez variável</td></tr><tr><td>Delta</td><td>Cadeias paralelas</td><td>Pick-and-place rápido; baixa massa móvel</td><td>Espaço e capacidade de carga específicos</td></tr><tr><td>Stewart / hexápode</td><td>Seis pernas atuadas</td><td>Plataforma com até 6 GL; posicionamento</td><td>Curso e restrições das pernas</td></tr></table></div>
<h2>Complacência seletiva do SCARA</h2><p>Em montagem, alguma acomodação no plano pode ajudar uma peça a se alinhar, enquanto rigidez na direção vertical sustenta a inserção. “Selective Compliance” descreve comportamento direcional; não significa estrutura frouxa em todas as direções.</p>
<h2>Como comparar sem inventar especificações</h2><p>O gráfico de comparação da aula é qualitativo e didático. Não extraia dele velocidades em m/s ou percentuais reais de fabricantes. Compare tendência, depois peça dados concretos: alcance, carga, repetibilidade, ciclo, rigidez e condições de medição.</p>
<div class="worked"><h3>Escolha justificada</h3><p>Para montar pequenas peças sobre uma mesa, um SCARA pode oferecer movimentos adequados e rapidez. Para soldar superfícies com muitas orientações, um articulado com punho pode ser mais conveniente. Para transportar itens leves em ciclos muito curtos, considere Delta. A tarefa define os critérios; nenhum tipo vence todos eles.</p></div>''','Polar e SCARA podem ser RRP. Como distingui-los?','Pela disposição dos eixos e pela geometria dos movimentos. A sequência de letras não descreve sozinha a arquitetura inteira.')

m('workspace','Espaço de trabalho e orientação','Mecânica','Calcule volumes idealizados e distinga alcance de destreza.', [('A','9-14'),('A','32'),('M','20-26')], '''
<h2>Alcançável não é sempre utilizável</h2><p>O espaço de trabalho é o conjunto de posições que o efetuador consegue alcançar sob limites de juntas e geometria. O espaço de trabalho destro acrescenta a exigência de orientações desejadas. A região segura de operação depende também de colisões, ferramentas, objetos e barreiras. Um desenho geométrico do volume não é automaticamente uma autorização para operar em toda a região.</p>
<h2>Modelos geométricos</h2><div class="formula">Cartesiano: V = Δx Δy Δz<br>Cilíndrico, rotação completa: V = π(r_max² − r_min²) h<br>Cilíndrico, setor de β rad: V = (β/2)(r_max² − r_min²) h<br>Casca esférica completa: V = (4π/3)(r_max³ − r_min³)</div>
<p>Essas fórmulas pressupõem eixos ideais, cursos independentes e ausência de interferência mecânica. Para setores esféricos, use os limites dos ângulos; não aplique a esfera completa quando o robô só varre uma faixa. Comparações da aula que assumem 360° e comprimentos iguais são simplificações didáticas.</p>
<h2>Punho e referencial</h2><p>Roll é rolamento, pitch é arfagem e yaw é guinada. Os eixos e a ordem de rotações precisam ser declarados, pois três ângulos sem convenção não identificam uma orientação de forma inequívoca. A apostila mostra punhos RT e TRT e uma sequência de Euler x–z–x. Um punho de três eixos ideal amplia a orientação, mas possui limites e singularidades reais.</p>
<p>O TCP, ponto central da ferramenta, pode ficar afastado do centro do punho. Ao girar o punho, esse ponto pode mudar de posição. Não suponha que orientar uma ferramenta com comprimento a preserve seu TCP sem compensação do restante do braço.</p>
<div class="worked"><h3>Cilindro com vazio central</h3><p>Com r máximo = 0,8 m, r mínimo = 0,2 m e curso vertical = 0,5 m, V = π(0,64 − 0,04) × 0,5 = <strong>0,3π ≈ 0,942 m³</strong>. Para apenas meia volta, o volume ideal é metade: aproximadamente 0,471 m³.</p></div>''','Um ponto alcançável pode não aceitar a orientação pedida?','Sim. A posição pode estar no espaço alcançável, mas fora do conjunto de poses permitidas pelos limites de juntas e pela geometria.')

m('garras','Garras e ferramentas','Mecânica','Escolha a preensão e dimensione a força em um modelo de atrito.', [('A','14-17'),('M','3-5'),('M','31')], '''
<h2>O efetuador depende do objeto</h2><p>Garras mecânicas fazem contato por dedos; ventosas usam diferença de pressão; dispositivos magnéticos precisam de material apropriado; ferramentas podem soldar, pulverizar ou medir sem agarrar. Forma, massa, fragilidade, rugosidade e ambiente definem a escolha. Uma garra para bloco rígido não serve automaticamente para vidro fino ou tecido.</p>
<p>Garras de dois dedos podem ter movimentos paralelos ou angulares. Mecanismos articulados mudam a orientação das superfícies de contato; molas ou dedos adaptativos ajudam a acomodar variações. Sensores de força e presença de peça permitem confirmar a preensão e limitar o esforço.</p>
<h2>Um cálculo de atrito com hipóteses explícitas</h2><p>Considere uma peça vertical segurada entre p contatos iguais, com força normal N por contato e coeficiente de atrito μ. Sem aceleração vertical, o atrito total disponível é pμN. Para sustentar o peso mg, exige-se pμN ≥ mg.</p><div class="formula">N_por_contato ≥ S × m(g + a)/ (p μ)</div><p>S é um fator de margem escolhido para o exercício e a é uma aceleração vertical para cima. A força total de aperto pode ter outra definição no catálogo: confirme se é a soma das forças ou a força por dedo. O coeficiente de atrito não é universal e muda com superfície e contaminação.</p>
<div class="worked"><h3>Dois dedos e uma peça de 1 kg</h3><p>Para μ = 0,3, p = 2 e margem didática S = 2, sem aceleração: N ≥ 2 × 1 × 9,81 / (2 × 0,3) = <strong>32,7 N por dedo</strong>. Os dois contatos somam 65,4 N de forças normais. Verifique se esse aperto não danifica a peça.</p></div>
<h2>Ventosa e centro de massa</h2><p>No modelo ideal, força de sucção é diferença de pressão × área efetiva. Vazamentos, porosidade, orientação e esforços de desprendimento reduzem a capacidade. Uma peça com centro de massa afastado cria um momento além da força vertical; segurar o peso não garante resistir à rotação.</p>
<h2>Carga útil</h2><p>Considere peça, garra, adaptadores e acessórios. A posição do centro de massa e a inércia também importam, especialmente em acelerações e com o braço estendido.</p>''','Se o atrito cair pela metade, o que acontece à força normal exigida nesse modelo?','Ela dobra, mantendo massa, número de contatos, aceleração e margem constantes.')

m('atuadores','Atuadores elétricos, hidráulicos e pneumáticos','Mecânica','Entenda como energia vira movimento e compare as alternativas.', [('A','17-24'),('C','21-23'),('M','6-8')], '''
<h2>Energia, comando e ação</h2><p>Um atuador converte energia em movimento ou força. O controlador produz uma ordem; o atuador realiza a ação física. Entre eles, um driver ou uma válvula controla potência. Não confunda o sensor, que mede, com o atuador, que age.</p>
<table><tr><th>Tipo</th><th>Princípio</th><th>Vantagens e limitações</th></tr><tr><td>Elétrico</td><td>Interação eletromagnética</td><td>Controle e integração convenientes; avaliar aquecimento, torque, alimentação e transmissão.</td></tr><tr><td>Hidráulico</td><td>Pressão e fluxo de fluido</td><td>Alta força em certas aplicações; requer bomba, válvulas, tubulações e atenção a vazamentos.</td></tr><tr><td>Pneumático</td><td>Ar comprimido</td><td>Útil em movimentos simples e garras; compressibilidade dificulta posicionamento fino.</td></tr></table>
<h2>Pressão não é força</h2><div class="formula">F_ideal = Δp × A<br>p em Pa (N/m²), A em m², F em N</div><p>A força de um cilindro depende da área efetiva e da diferença de pressão. No lado da haste, a área útil costuma ser menor. Atrito e perdas reduzem a força real. Vazão influencia a velocidade, e o sistema de válvulas precisa controlar o movimento.</p>
<div class="worked"><h3>Cilindro ideal</h3><p>Com Δp = 500 kPa e A = 0,001 m², F = 500.000 × 0,001 = <strong>500 N</strong>. Isso não quer dizer 500 kg: uma força de 500 N equilibra aproximadamente 51 kg de massa sob g = 9,81 m/s², no modelo estático ideal.</p></div>
<h2>Acionamento direto e indireto</h2><p>No direto, o atuador se acopla à junta sem uma transmissão intermediária de redução. No indireto, redutores, correias, cabos ou outros mecanismos adaptam velocidade e torque ou transferem o movimento. O indireto pode colocar motores perto da base. O direto evita certas folgas, mas pede um atuador capaz de fornecer o torque na velocidade da junta.</p>
<p>As comparações antigas da apostila refletem o contexto do livro. Não trate frases como “um tipo é sempre mais rápido” como lei universal: desempenho depende do equipamento e da tarefa.</p>''','Qual grandeza mais diretamente relaciona área do pistão e força em um cilindro ideal?','A diferença de pressão: F = Δp × A.')

m('motores','Motores CC, BLDC, passo e servos','Eletrônica','Entenda comutação, passos, PWM e realimentação.', [('A','19-24'),('C','21-23'),'pwm'], '''
<h2>Motor CC e comutação</h2><p>Em um motor de corrente contínua com escovas, o comutador alterna a corrente dos enrolamentos conforme o rotor gira. O torque depende da corrente no modelo usual e a velocidade resulta do equilíbrio entre tensão, força contraeletromotriz, carga e perdas. Inverter a polaridade pode inverter o sentido, com um circuito adequado.</p><p>No BLDC, a comutação é eletrônica: o driver energiza fases de acordo com a posição ou uma estimativa do rotor. Ímãs permanentes ficam no rotor em configurações comuns. Não basta ligar uma tensão contínua arbitrária nas três fases para obter operação controlada.</p>
<h2>Motor de passo</h2><p>O driver alterna fases para avançar a posição em incrementos. No modelo ideal, contar pulsos estima a posição. Se a carga, aceleração ou velocidade excederem a capacidade, o motor pode perder passos. Em malha aberta, o controlador pode não perceber essa perda.</p><div class="formula">Passos por volta = 360° / ângulo do passo<br>Com passo de 1,8°: 200 passos/volta</div><p>Meio passo intercala estados de excitação. Microstepping regula correntes para subdividir o passo e suavizar o movimento. Aumentar o número de micro passos aumenta a resolução de comando; não garante igual ganho de exatidão sob carga.</p>
<h2>Servo é um sistema de controle</h2><p>Um servossistema usa realimentação para seguir uma referência de posição, velocidade ou torque. Pode empregar tipos diferentes de motor. Um servo de hobby reúne motor, transmissão, sensor e controle em um conjunto; seu sinal de comando não deve ser confundido com o PWM de potência aplicado ao motor.</p>
<h2>PWM</h2><p>Pulse Width Modulation varia a fração de tempo em que um sinal fica ligado. Duty cycle D = tempo ligado / período. No modelo ideal de chaveamento entre 0 e V, a média é DV. A função analogWrite em pinos PWM do Arduino gera uma onda retangular, e não necessariamente uma tensão analógica constante.</p>
<div class="worked"><h3>Exercício combinado</h3><p>Um motor de 1,8° recebe 50 passos completos: avanço ideal = 90°. Um PWM de 25% sobre 12 V tem média ideal de 3 V. Isso não garante 25% da velocidade máxima: carga, circuito e motor interferem.</p></div>''','Mais micro passos garantem proporcionalmente mais precisão?','Não. Eles subdividem o comando, mas atrito, carga, torque incremental e erros mecânicos limitam a precisão real.')

m('transmissoes','Redutores e transmissões','Mecânica','Calcule velocidade, torque, eficiência e efeitos da folga.', [('A','24-26'),('C','24-27'),('M','28-30')], '''
<h2>Trocar velocidade por torque</h2><p>Um redutor adapta a velocidade do motor à junta. Defina N = ω_entrada / ω_saída. Para redução, N &gt; 1. No modelo ideal, potência se conserva: τ_entrada ω_entrada = τ_saída ω_saída. Com rendimento η, só parte da potência chega à saída.</p><div class="formula">ω_saída = ω_entrada / N<br>τ_saída = η N τ_entrada<br>P_saída = η P_entrada</div><p>Declare a definição de relação de transmissão: alguns textos usam a razão inversa. Nunca aplique uma fórmula sem saber qual eixo está no numerador.</p>
<div class="worked"><h3>Exemplo da aula, explicado</h3><p>Motor com 1 N·m, N = 50 e η = 0,8: τ_saída = 0,8 × 50 × 1 = <strong>40 N·m</strong>. A 3.000 rpm, a saída fica a 60 rpm. A potência de entrada é cerca de 314,16 W e a de saída 251,33 W. A diferença representa perdas neste ponto de operação.</p></div>
<h2>Escolher a transmissão</h2><ul><li>Engrenagens: compactas; podem introduzir folga e ruído.</li><li>Correias: permitem afastar eixos; avaliar elasticidade, tensão e deslizamento conforme o tipo.</li><li>Correntes: transmitem força entre eixos; avaliar lubrificação e folga.</li><li>Cabos: transferem movimento com baixa massa móvel; exigem tensão e controle de elasticidade.</li><li>Fuso: converte rotação em translação com avanço definido pelo passo.</li><li>Harmonic drive e redutores planetários: soluções específicas para torque, compactação e precisão.</li></ul>
<h2>Folga e histerese</h2><p>Ao inverter o sentido, pode haver um intervalo em que o motor gira e a saída ainda não se move. Isso é backlash ou folga. Elasticidade provoca deformação sob carga; histerese significa que o comportamento depende do histórico. Um encoder no motor pode não registrar integralmente esses efeitos no efetuador.</p>
<p>Redução muito alta não é uma solução gratuita: pode alterar eficiência, velocidade, inércia percebida e capacidade de ser movimentado por forças externas. Dimensione para o perfil de torque e velocidade da tarefa.</p>''','Um redutor 10:1 com eficiência de 90% entrega quanto torque para uma entrada de 2 N·m?','18 N·m, usando N = 10 e τ_saída = ηNτ_entrada.')
