from curriculum import m, MODULES

m('sensores','Sensores e aquisição de dados','Eletrônica','Compare o que cada sensor mede e os erros que introduz.', [('A','35-38'),('C','28-31'),('M','9-11')], '''
<h2>Estado interno e ambiente</h2><p>Sensores internos medem o próprio robô: posição de junta, velocidade, corrente, temperatura ou torque. Externos medem o ambiente: objetos, obstáculos e condições de contato. A classificação depende do uso, não apenas do nome: um sensor de força pode medir esforço em uma junta ou interação na ferramenta.</p>
<table><tr><th>Sensor</th><th>Informação</th><th>Cuidado</th></tr><tr><td>Potenciômetro</td><td>Posição associada à tensão do cursor</td><td>Contato, desgaste e faixa angular</td></tr><tr><td>Tacômetro</td><td>Tensão proporcional à velocidade</td><td>Calibração e ruído</td></tr><tr><td>Encoder / resolver</td><td>Movimento ou ângulo</td><td>Resolução, referência e processamento</td></tr><tr><td>Ultrassom</td><td>Distância por tempo de voo</td><td>Reflexões e geometria do alvo</td></tr><tr><td>Infravermelho / óptico</td><td>Luz, proximidade ou distância conforme a tecnologia</td><td>Iluminação e refletância</td></tr><tr><td>Hall / indutivo / capacitivo</td><td>Campo magnético ou presença de materiais</td><td>Material e alcance específico</td></tr><tr><td>Strain gauge</td><td>Deformação por variação de resistência</td><td>Montagem, temperatura e calibração</td></tr><tr><td>IMU</td><td>Aceleração específica e velocidade angular</td><td>Viés, gravidade e deriva</td></tr><tr><td>Câmera, LiDAR e radar</td><td>Imagem ou medidas do ambiente</td><td>Oclusões, resolução, sincronização e alcance</td></tr></table>
<h2>Analógico e digital</h2><p>Um sinal analógico varia continuamente em uma faixa. Um conversor analógico-digital (ADC) representa essa faixa por números. Para b bits há 2ᵇ códigos possíveis. Um sinal digital não é automaticamente correto: ruído, atrasos e perdas ainda precisam ser tratados. Antes de ler, verifique níveis elétricos e referência de tensão.</p>
<div class="worked"><h3>Ultrassom e ida e volta</h3><p>Se um eco retorna em 4 ms e a velocidade do som é assumida como 343 m/s, d = ct/2 = 343 × 0,004 / 2 = <strong>0,686 m</strong>. Divide-se por dois porque o som percorreu o caminho até o objeto e de volta. Temperatura e geometria alteram o resultado real.</p></div>
<h2>Critérios de seleção</h2><p>Compare faixa, resolução, exatidão, repetibilidade, tempo de resposta, ruído, interface e condições ambientais. Para controlar um movimento rápido, uma medição muito atrasada pode ser mais problemática que uma resolução um pouco menor.</p>''','Por que alta resolução não garante uma boa medida?','Porque calibração, viés, ruído, montagem, temperatura e atraso podem produzir erros maiores que o incremento digital.')

m('encoders','Encoders, resolver e código Gray','Eletrônica','Calcule incrementos e entenda posição absoluta, quadratura e referência.', [('A','35-37'),('C','30-34'),('M','9-11'),('M','27')], '''
<h2>Incremental e absoluto</h2><p>O encoder incremental gera transições ligadas ao movimento. Um contador estima deslocamento a partir de uma referência. Os canais A e B em quadratura permitem inferir sentido pela ordem das transições. Um canal Z pode marcar uma referência por volta; ele não informa sozinho todas as voltas acumuladas.</p><p>O absoluto fornece um código de posição. Um modelo single-turn identifica a posição dentro de uma volta; rastrear várias voltas exige tecnologia ou estado adicional. A recuperação após desligamento depende do dispositivo e do sistema, especialmente para posição multivoltas.</p>
<h2>Resolução e decodificação</h2><div class="formula">Incremento angular = 360° / C<br>C = contagens efetivas por volta<br>Com encoder no motor e redução N:<br>incremento ideal da junta = 360° / (C N)</div><p>Não confunda pulsos por volta (PPR) com contagens efetivas (CPR). Uma decodificação x4 pode contar quatro bordas por ciclo A/B. Os fabricantes nem sempre usam as siglas do mesmo modo: leia a definição.</p>
<div class="worked"><h3>As duas convenções dos materiais</h3><p>Encoder de 180 contagens por volta: incremento = 2°. Com redução N = 10: incremento da junta = 0,2°. A apostila também chama R = Δθ/(2N) de resolução espacial: nesse exemplo, R = 0,1°. Isso corresponde à metade do incremento, relacionada ao limite ideal de quantização. A aula de manipuladores usa “resolução” para o incremento inteiro. Indique sua convenção.</p></div>
<h2>Por que Gray?</h2><p>Na contagem binária, passar de 011 para 100 muda três bits. Se a leitura ocorre durante uma transição, pequenas diferenças de tempo podem gerar um código intermediário. Na sequência Gray, posições vizinhas diferem em um bit, reduzindo essa ambiguidade. Gray não elimina todos os tipos de ruído ou defeito.</p>
<h2>Resolver</h2><p>O resolver é um transdutor rotativo que produz sinais relacionados a seno e cosseno do ângulo. O processamento pode estimar o ângulo usando atan2(seno, cosseno), que preserva o quadrante. Uma razão seno/cosseno isolada não resolve toda a orientação e falha quando o denominador é zero.</p>
<p>Um sensor no motor melhora a resolução angular ideal após redução, mas não mede automaticamente folga, flexão ou deformação depois dele.</p>''','Com 1.000 ciclos por volta e leitura x4, qual é o incremento angular?','Há 4.000 contagens por volta; o incremento é 360/4.000 = 0,09°.')

m('controle','Malhas de controle e PID','Controle','Construa a realimentação e calcule os três termos do controlador.', [('C','35-38'),('M','12-13'),('A','26-30')], '''
<h2>Referência, erro, ação e planta</h2><p>A referência r é o valor desejado; y é o valor medido; o erro é e = r − y. O controlador calcula a ação u aplicada ao sistema físico, chamado planta. O sensor fecha a malha trazendo uma nova medição. Em malha aberta, o comando não é corrigido pela medição da variável controlada.</p><div class="formula">Referência → comparação → controlador → driver → motor/planta<br>                         ↑                         ↓<br>                         └──── sensor/medição ─────┘<br>e(t) = r(t) − y(t)<br>u(t) = Kp e(t) + Ki ∫e(t)dt + Kd de(t)/dt</div>
<h2>O papel de cada termo</h2><p><strong>P</strong> reage ao erro atual. Aumentar Kp pode acelerar a correção, mas pode aumentar oscilações e esforço. <strong>I</strong> acumula erro e pode reduzir um desvio persistente; saturação pode provocar windup, acumulação excessiva da integral. <strong>D</strong> responde à variação e pode contribuir com amortecimento, mas amplifica ruído quando implementado sem cuidado.</p><p>PI usa P e I; PD usa P e D. Liga/desliga alterna ações com o sinal do erro, podendo usar histerese para evitar comutação excessiva. O melhor controlador depende do sistema; não há ganhos universais.</p>
<h2>Implementação discreta</h2><div class="formula">I_k = I_(k−1) + e_k Ts<br>D_k ≈ (e_k − e_(k−1))/Ts<br>u_k = Kp e_k + Ki I_k + Kd D_k<br>f_s = 1/Ts</div><p>O período Ts é em segundos. Considere filtros, limites do atuador, anti-windup, ruído, atraso e mudanças de referência. Controle em cascata pode usar uma malha externa de posição, uma intermediária de velocidade e uma interna de corrente, com escalas de tempo compatíveis.</p>
<div class="worked"><h3>Um instante do PID</h3><p>Para erro atual 2, anterior 1, Ts = 0,1 s, integral anterior 0, Kp = 3, Ki = 1 e Kd = 0,2: I = 0,2; D = 10; u = 6 + 0,2 + 2 = <strong>8,2</strong>. As unidades e a saturação de u dependem da aplicação. Não aplique ganhos arbitrários a um motor real.</p></div>''','Se Ts = 5 ms, qual a frequência de amostragem?','Ts = 0,005 s; f_s = 1/0,005 = 200 Hz.')

m('embarcados','Controladores, firmware e tempo real','Computação','Distribua tarefas entre microcontrolador, computador e supervisão.', [('C','8-12'),('C','39-42'),('C','66')], '''
<h2>Microcontrolador e computador embarcado</h2><p>Um microcontrolador integra processamento e periféricos úteis para ler entradas, gerar PWM, contar encoder e controlar tarefas simples. Um computador embarcado costuma oferecer mais memória e capacidade para visão, mapas e algoritmos complexos. A aula cita Arduino, STM32 e ESP32 como exemplos de plataformas e famílias, não como sistemas equivalentes em todos os recursos.</p>
<p>Uma arquitetura distribuída pode usar um computador para planejar e um microcontrolador para controlar motores. A fronteira precisa definir mensagens, frequência, unidades, validade e comportamento na perda de comunicação. Um comando antigo não deve permanecer válido indefinidamente.</p>
<h2>Tempo real significa cumprir prazos</h2><p>Não é sinônimo de processador rápido. Um sistema de tempo real precisa responder dentro de prazos definidos. Latência é o atraso; jitter é a variação desse atraso. Um laço de controle pode exigir uma medição e uma ação a cada intervalo. Se a tarefa de imagem atrasar esse laço, a arquitetura pode precisar separar os níveis.</p>
<h2>Firmware, Linux e interrupções</h2><p>Firmware executa o comportamento embarcado. Pode rodar diretamente no hardware ou sobre um sistema operacional de tempo real. Linux oferece recursos úteis para aplicações complexas, mas uma instalação comum não garante automaticamente os prazos de controle. Interrupções atendem eventos; devem ser curtas e coordenadas com o restante do código. Bloquear uma rotina com espera longa pode impedir atender sensores ou comandos.</p>
<div class="worked"><h3>Plano de tarefas de um seguidor de linha</h3><p>Leitura e controle lateral: tarefa periódica. Contagem de encoder: periférico ou interrupção. Interface com o usuário: tarefa mais lenta. Registro de dados: tarefa que não pode bloquear o controle. Um watchdog monitora se o software continua atendendo condições esperadas e aciona recuperação conforme o projeto.</p></div>
<h2>Verificações úteis</h2><p>Cheque consumo de memória, níveis de tensão, periféricos disponíveis, taxa de amostragem e capacidade de processamento. Um programa que funciona sem carga computacional adicional pode falhar quando visão e comunicação são ativadas.</p>''','Por que um processador rápido pode não atender tempo real?','Porque atrasos imprevisíveis, bloqueios e escalonamento podem impedir o cumprimento dos prazos, mesmo com alta capacidade média de processamento.')

m('potencia','Drivers, ponte H e alimentação','Eletrônica','Separe sinal de controle de potência e estime energia disponível.', [('C','43-48'),('A','19-24'),'pwm'], '''
<h2>O controlador comanda; o driver fornece potência</h2><p>Uma saída lógica não foi feita para alimentar diretamente um motor de vários amperes. O driver recebe sinais e controla a energia entregue ao atuador. Uma ponte H usa chaves para inverter a polaridade em motores CC. Acionar indevidamente chaves do mesmo ramo pode criar curto entre os polos da alimentação; drivers e temporização precisam evitar isso.</p>
<p>Motores são cargas indutivas. A corrente não desaparece instantaneamente ao desligar, e o circuito precisa prever recirculação e transientes. Motores de passo e BLDC exigem drivers e sequências de comutação adequados. A seleção considera tensão, corrente contínua e de pico, dissipação, proteções e sinal de comando.</p>
<h2>Potência e capacidade da fonte</h2><div class="formula">P_elétrica = VI<br>E_nominal(Wh) ≈ V_nominal × capacidade(Ah)<br>Autonomia(h) ≈ energia_utilizável(Wh) / potência_média(W)</div><p>Ah mede capacidade de carga elétrica; Wh mede energia. Duas baterias com o mesmo Ah e tensões diferentes não têm a mesma energia nominal. A potência média para autonomia é diferente da potência de pico para dimensionar alimentação.</p>
<div class="worked"><h3>Contas apresentadas na aula</h3><p>Um motor a 24 V e 5 A consome 120 W naquele ponto. Quatro nas mesmas condições somam 480 W, antes de outros equipamentos e perdas. Uma bateria de 12 V e 10 Ah tem energia nominal aproximada de 120 Wh. Para 60 W médios e fração utilizável didática de 80%, autonomia ≈ 96/60 = <strong>1,6 h</strong>.</p></div>
<h2>Tensões diferentes e ruído</h2><p>Um robô pode usar 24 V em motores, 5 V em sensores e 3,3 V na lógica. Conversores DC–DC adaptam essas tensões. Referências elétricas, compatibilidade de sinais, cabos, desacoplamento e proteção precisam ser projetados para impedir que ruído de motores corrompa medições ou reinicie o controlador.</p>
<p>Bateria real depende de descarga, temperatura, envelhecimento e limites do gerenciamento. Desligamento de emergência e isolamento de energia são funções distintas. Os exercícios aqui são estimativas didáticas, não projetos de ligação elétrica.</p>''','Uma bateria de 24 V e 5 Ah tem aproximadamente quantos Wh nominais?','120 Wh, usando 24 × 5. A energia realmente utilizável depende das condições e dos limites da bateria.')

m('comunicacao','Comunicação e ROS','Computação','Escolha interfaces por distância, ruído e prazo; entenda mensagens robóticas.', [('C','41'),('C','49-51'),'ros'], '''
<h2>Não é apenas transmitir bytes</h2><p>Além da taxa de dados, escolha uma interface pela distância, número de dispositivos, robustez, custo e requisitos de tempo. Combine formato das mensagens, unidades, ordem de bytes, identificação, detecção de erro e resposta a falhas. Uma mensagem recebida corretamente pode estar velha ou em um referencial diferente do esperado.</p>
<table><tr><th>Interface</th><th>Uso didático</th><th>Atenção</th></tr><tr><td>UART</td><td>Comunicação serial assíncrona</td><td>Baud rate, formato e níveis elétricos</td></tr><tr><td>I²C</td><td>Barramento endereçado com SDA e SCL</td><td>Pull-ups, capacitância e endereços</td></tr><tr><td>SPI</td><td>Comunicação síncrona com seleção de dispositivo</td><td>Mais linhas, modo de clock</td></tr><tr><td>CAN</td><td>Mensagens em rede distribuída</td><td>Arbitragem, terminação e carga do barramento</td></tr><tr><td>RS-485</td><td>Sinalização diferencial em ligações robustas</td><td>Define camada elétrica; ainda precisa de protocolo</td></tr><tr><td>USB / Ethernet</td><td>Periféricos e computadores</td><td>Latência e requisitos do sistema</td></tr><tr><td>Sem fio</td><td>Supervisão e robôs móveis</td><td>Interferência, perdas e cobertura</td></tr></table>
<h2>Um complemento: ROS</h2><p>ROS é um conjunto de ferramentas e infraestrutura de software para robótica. Nós trocam informações por interfaces. Topics transportam fluxos de dados publicados para assinantes; services seguem pedido e resposta; actions representam tarefas que podem demorar, com resultado, feedback e possibilidade de cancelamento. A documentação de design do ROS 2 explica essas diferenças.</p>
<div class="worked"><h3>Escolha por comportamento</h3><p>Uma câmera envia imagens continuamente por um topic. Consultar uma configuração pode usar um service. “Navegue até o laboratório” combina meta, andamento e resultado, apropriados para uma action. Isso é uma escolha de organização do software, não uma garantia de segurança ou de tempo real.</p></div>
<h2>Integração entre níveis</h2><p>Mensagens entre planejador e controle de motor devem ter validade temporal. Se a conexão cair, o controlador local precisa executar o comportamento previsto pelo projeto. Redundância e diagnóstico também devem ser verificados: dois canais que falham pela mesma causa não resolvem o problema.</p>''','Qual interface ROS combina meta, progresso e cancelamento?','Uma action, útil para tarefas demoradas como navegação até um destino.')

m('cinematica','Cinemática direta e inversa','Matemática aplicada','Calcule um braço planar e entenda transformações de referenciais.', [('C','52-54'),('C','18-19'),('A','32'),'direta','inversa'], '''
<h2>Dois problemas diferentes</h2><p>Na cinemática direta, conhecemos as coordenadas das juntas q e calculamos a pose do efetuador x = f(q). Na inversa, buscamos valores de q que produzam uma pose desejada. A escrita q = f⁻¹(x) do slide é uma abreviação: nem sempre existe uma inversa única. Pode haver várias soluções, nenhuma, ou famílias de soluções.</p>
<h2>Exemplo de dois elos no plano</h2><p>Considere L1 e L2, ângulo q1 relativo ao eixo x e q2 relativo ao primeiro elo. A orientação do segundo elo em relação à base é q1 + q2.</p><div class="formula">x = L1 cos(q1) + L2 cos(q1 + q2)<br>y = L1 sen(q1) + L2 sen(q1 + q2)<br>φ = q1 + q2</div>
<div class="worked"><h3>Direta, passo a passo</h3><p>Com L1 = 1 m, L2 = 1 m, q1 = 0° e q2 = 90°: x = 1 + 0 = <strong>1 m</strong>; y = 0 + 1 = <strong>1 m</strong>; φ = 90°. O primeiro elo está horizontal e o segundo, vertical.</p></div>
<h2>Inversa geométrica</h2><div class="formula">c2 = (x² + y² − L1² − L2²)/(2 L1 L2)<br>q2 = ± arccos(c2)<br>q1 = atan2(y,x) − atan2(L2 sen(q2), L1 + L2 cos(q2))</div><p>Se |c2| &gt; 1, o alvo está fora do alcance geométrico ideal. Para x = y = 1 e L1 = L2 = 1, as soluções incluem (0°,90°) e (90°,−90°). Limites das juntas, colisões e orientação podem invalidar uma ou ambas. Este braço tem apenas dois GL; não pode escolher x, y e φ arbitrariamente como três valores independentes.</p>
<h2>Transformações homogêneas</h2><div class="formula">T = [ R  p ]<br>    [ 0  1 ]</div><p>No espaço, R é uma matriz 3×3 de rotação e p é uma coluna de translação, formando T 4×4. As transformações de uma cadeia são multiplicadas em ordem compatível: T_base,ferramenta = T_base,1 T_1,2 ... T_n,ferramenta. A ordem importa e cada transformação precisa declarar os referenciais conectados.</p>
<p>Métodos numéricos de inversa atualizam uma estimativa das juntas para reduzir erro. Uma estimativa inicial ruim, singularidades ou limites podem dificultar convergência.</p>''','Um alvo em (3 m, 0) pode ser alcançado por dois elos de 1 m?','Não. O alcance máximo geométrico é 2 m; o cálculo dá |c2| > 1.')

m('jacobiano','Jacobiano, singularidades e redundância','Matemática aplicada','Relacione velocidades e reconheça configurações problemáticas.', [('M','33-35'),('C','54'),'singular'], '''
<h2>Uma relação local de velocidades</h2><p>O Jacobiano J(q) depende da configuração do robô. Ele transforma velocidades das juntas em velocidade do efetuador. É uma relação local: descreve o movimento instantâneo em torno da configuração atual, não substitui a cinemática direta para deslocamentos finitos.</p><div class="formula">ẋ = J(q) q̇<br>Para pose espacial: [v; ω] = J(q) q̇</div><p>v contém velocidades lineares e ω, velocidades angulares. Se a tarefa tem m componentes e o robô n coordenadas independentes, J normalmente tem m linhas e n colunas.</p>
<h2>Jacobiano do braço planar 2R</h2><div class="formula">J = [−L1 sen(q1) − L2 sen(q1+q2), −L2 sen(q1+q2)]<br>    [ L1 cos(q1) + L2 cos(q1+q2),  L2 cos(q1+q2)]<br>det(J) = L1 L2 sen(q2)</div><p>Essa matriz relaciona q̇1, q̇2 às velocidades ẋ, ẏ, sem incluir uma orientação independente. Com os elos alinhados, q2 = 0 ou π, o determinante é zero e o posto diminui. Nessa configuração, o robô perde uma direção de velocidade cartesiana instantânea.</p>
<div class="worked"><h3>O braço totalmente esticado</h3><p>Com q1 = q2 = 0, as duas colunas de J apontam para a direção y. Pequenas rotações produzem movimento lateral instantâneo; não há velocidade instantânea na direção x. Isso não significa que o braço nunca possa retrair: ele pode sair da configuração e então mudar x.</p></div>
<h2>Quando a matriz não é quadrada</h2><p>O critério det(J) = 0 vale para matriz quadrada. Em geral, analise perda de posto, valores singulares ou indicadores apropriados. Perto de uma singularidade, tentar produzir certas velocidades cartesianas pode exigir velocidades articulares muito altas.</p>
<h2>Redundância</h2><p>Com mais GL do que a tarefa exige, podem existir movimentos de juntas que preservam a tarefa instantaneamente. Eles podem melhorar postura ou afastar obstáculos, mas exigem escolha de critérios e respeito aos limites. Redundância não garante uma solução segura nem remove todas as singularidades.</p>''','Pode-se aplicar det(J) = 0 a qualquer Jacobiano?','Não. Determinante é definido para matrizes quadradas. Para Jacobianos retangulares, avalie o posto e critérios apropriados.')

m('desempenho','Resolução, precisão e repetibilidade','Controle','Separe incremento, proximidade do alvo e dispersão das repetições.', [('A','30-34'),('A','37'),('M','27'),('C','33-34')], '''
<h2>Três perguntas</h2><p><strong>Resolução</strong>: qual o menor incremento distinguível ou comandável? <strong>Precisão/exatidão de posicionamento</strong>: quão perto o robô chega da posição desejada? <strong>Repetibilidade</strong>: quão próximas entre si são posições obtidas ao repetir a operação nas mesmas condições? Os materiais usam “precisão” no sentido de proximidade do alvo; em metrologia, o vocabulário pode separar precisão de exatidão.</p>
<p>Um sistema pode voltar consistentemente a um ponto deslocado do alvo. Tem boa repetibilidade e erro sistemático. Calibrar pode reduzir esse desvio, mas não corrige necessariamente a dispersão aleatória causada por folga, flexão ou ruído.</p>
<div class="worked"><h3>Alvo de 100 mm</h3><p>Resultados 102,0; 102,1; 102,0 mm ficam agrupados, mas longe do alvo. Média ≈ 102,033 mm e erro médio ≈ +2,033 mm. Isso sugere alta repetibilidade relativa ao pequeno espalhamento e baixa exatidão em relação ao alvo. Resultados 98, 100 e 102 mm têm média no alvo, mas grande dispersão; uma média boa não garante cada ciclo bom.</p></div>
<h2>Resolução angular e erro linear</h2><div class="formula">Pequeno deslocamento tangencial: Δs ≈ r Δθ<br>Δθ precisa estar em radianos</div><p>Para r = 0,5 m e Δθ = 0,1° = 0,001745 rad, Δs ≈ 0,873 mm. O mesmo incremento angular causa um deslocamento maior longe do eixo. Assim, a resolução cartesiana de braços com juntas rotativas varia no espaço.</p>
<h2>Quantização não explica tudo</h2><p>Metade do incremento é um limite ideal de arredondamento em um eixo quando se escolhe o ponto endereçável mais próximo. Não é a precisão total de um robô real. Calibração, erros geométricos, temperatura, carga, folga e flexibilidade também contribuem.</p>
<h2>Como comparar especificações</h2><p>Declare direção de aproximação, carga, postura, velocidade, número de ciclos e método de medição. Não transforme “±0,1 mm de repetibilidade” automaticamente em “±0,1 mm de erro absoluto”. Condições diferentes podem mudar o desempenho.</p>''','Um robô que sempre para 3 mm à direita do alvo tem necessariamente má repetibilidade?','Não. Ele pode repetir muito bem a mesma posição incorreta; apresenta um desvio sistemático em relação ao alvo.')

m('dinamica','Dinâmica, trajetórias e complacência','Controle','Entenda torque, aceleração, estabilidade e deformação sob carga.', [('A','30-35'),('M','32')], '''
<h2>Cinemática descreve; dinâmica explica esforços</h2><p>A cinemática relaciona posições e velocidades. A dinâmica relaciona movimento e forças/torques, incluindo massa, inércia, gravidade e atrito. Um braço pode alcançar uma pose geometricamente e ainda não suportar nela a carga ou a aceleração solicitada.</p>
<h2>Perfil de velocidade e ciclo</h2><p>Um movimento costuma acelerar, manter uma velocidade e desacelerar. O perfil é trapezoidal quando há tempo para atingir o patamar. Em deslocamentos curtos, o perfil pode ser triangular. Exigir parada em muitos pontos aumenta tempo de ciclo, especialmente se cada ponto exigir estabilização.</p><div class="formula">Aceleração constante: v = v0 + at<br>Deslocamento no trecho: Δs = v0 t + (a t²)/2</div>
<h2>Oscilação e tempo de acomodação</h2><p>Um sistema subamortecido pode ultrapassar o alvo e oscilar antes de se acomodar. Um sistema sobreamortecido pode se aproximar lentamente sem oscilar. Tempo de acomodação é o tempo para entrar e permanecer em uma faixa de erro especificada. Estabilidade, em sentido de controle, não deve ser confundida com apenas “parar rápido”. Um sistema estável ainda pode ter resposta transitória inadequada para a tarefa.</p>
<h2>Rigidez e complacência</h2><div class="formula">Modelo linear em uma direção: F = k δ<br>Rigidez k = F/δ<br>Complacência C = δ/F = 1/k</div><p>Alta complacência significa maior deformação para a mesma força, no modelo considerado. A apostila usa a expressão “resistir ao movimento”, que pode confundir esse significado; estude a relação física. Em três dimensões, rigidez e complacência são direcionais e podem ser representadas por matrizes.</p>
<div class="worked"><h3>Flexão sob carga</h3><p>Se k = 10.000 N/m e F = 20 N, δ = 20/10.000 = 0,002 m = <strong>2 mm</strong>. Dobrar k reduz a deformação para 1 mm. Em uma inserção, alguma acomodação pode ajudar, mas não se deseja perder controle nem danificar a peça.</p></div>
<p>Velocidade, carga, precisão e rigidez interagem; afirmações absolutas de desempenho precisam ser entendidas como tendências dos exemplos, não como leis para todas as máquinas.</p>''','O que acontece à deformação ao dobrar a rigidez, com a mesma força?','Ela cai pela metade no modelo linear δ = F/k.')

m('programacao','Programação, PTP e trajetória contínua','Computação','Entenda ensino de pontos, interpolação e integração com a célula.', [('A','26-30'),('A','38')], '''
<h2>Programar uma tarefa robótica</h2><p>Um programa define movimentos, uso da ferramenta, condições e comunicação com outros equipamentos. Pode incluir pontos ensinados por um dispositivo de operação, programação textual e preparação offline. A apostila termina iniciando a seção de programação: ela não fornece, nesse trecho, um curso completo de uma linguagem específica. Aqui o complemento explica os conceitos necessários sem atribuir comandos a um fabricante.</p>
<h2>PTP e CP</h2><p><strong>PTP</strong>, ponto a ponto, busca atingir posições programadas. O caminho cartesiano entre elas não precisa seguir uma linha especificada. <strong>CP</strong>, trajetória contínua, controla o percurso, importante para soldagem, pintura ou aplicação de material. Uma interpolação cria referências intermediárias para construir esse movimento.</p>
<p>Interpolação em juntas pode produzir uma curva no espaço da ferramenta. Para movimento cartesiano linear, referências cartesianas precisam ser traduzidas em comandos articulares, considerando a cinemática. A terminologia histórica da apostila não significa que todos os controladores modernos tenham uma implementação interna idêntica.</p>
<h2>Controle por sequência e por repetição</h2><p>Sistemas de sequência limitada podem usar batentes, cames e sensores de fim de curso. Controle por repetição reproduz operações ensinadas. Realimentação externa acrescenta informações da célula, como presença da peça, situação da máquina ou medição por câmera; ela pode complementar PTP ou CP.</p>
<div class="worked"><h3>Pick-and-place em pseudocódigo</h3><pre class="formula">esperar peça presente e célula liberada<br>mover até aproximação de coleta<br>aproximar com perfil adequado<br>fechar garra e confirmar peça<br>retirar e mover até aproximação de entrega<br>posicionar, abrir e confirmar liberação<br>retornar; tratar falhas em qualquer etapa</pre><p>As aproximações evitam atravessar a peça ou a máquina. Cada “confirmar” exige um critério observável; uma pausa fixa sozinha não confirma sucesso.</p></div>
<h2>Teste e coordenadas</h2><p>Verifique referencial da base, ferramenta e peça. Trocar uma garra altera o TCP e a carga. Uma posição ensinada com ferramenta antiga pode deixar de representar a mesma posição física. Simulação e validação devem incluir obstáculos e limites.</p>''','Qual controle é mais adequado para seguir um cordão de solda?','Trajetória contínua (CP), com controle do percurso e perfil de movimento; chegar apenas aos pontos extremos não garante o cordão desejado.')

m('visao','Visão computacional e percepção','Percepção','Passe de pixels a informação e entenda calibração.', [('C','55-57'),('A','37-38'),'visao'], '''
<h2>Imagem não é interpretação</h2><p>Uma câmera produz dados de pixels. Percepção transforma esses dados em informação útil: onde está um objeto, qual é sua classe ou para onde uma linha aponta. Detecção localiza; classificação atribui categoria; segmentação separa regiões; rastreamento associa observações ao longo do tempo.</p>
<h2>Um pipeline simples para seguir uma linha</h2><ol><li>Capturar uma imagem com iluminação adequada.</li><li>Selecionar a região do chão importante para controle.</li><li>Converter a representação e reduzir ruído quando necessário.</li><li>Separar linha e fundo por um critério de intensidade ou cor.</li><li>Estimar a posição da linha e o erro lateral.</li><li>Transformar o erro em correção de movimento.</li></ol>
<h2>Limiarização</h2><p>Para um limiar T, um método binário pode marcar pixels com intensidade acima de T como 255 e os demais como 0. Para uma linha escura, o binário inverso pode ser mais apropriado. A documentação do OpenCV apresenta métodos simples, adaptativos e Otsu. Um limiar fixo pode falhar quando a iluminação muda.</p>
<div class="worked"><h3>Erro de uma linha</h3><p>Em uma imagem com largura 640 pixels, centro desejado x = 320 e centro detectado x = 280: e = 320 − 280 = <strong>40 pixels</strong>. A regra que transforma esse erro em velocidades das rodas depende da câmera, orientação, convenção de sinais e dinâmica. Pixel não é automaticamente metro.</p></div>
<h2>RGB, RGB-D e calibração</h2><p>RGB mede cor; RGB-D combina imagem com estimativa de profundidade. Calibração intrínseca descreve parâmetros como distância focal, ponto principal e distorção. Calibração extrínseca relaciona posição e orientação da câmera a outro referencial, como a base do robô. Uma coordenada de objeto na câmera só pode orientar a garra após as transformações apropriadas.</p>
<p>Oclusão, reflexos, textura, ruído e desfoque podem comprometer a percepção. Redes neurais ampliam capacidades, mas ainda precisam de dados, avaliação e comportamento previsto quando a confiança ou a qualidade da imagem é insuficiente.</p>''','Detectar o centro de um objeto em pixels basta para posicionar uma garra em metros?','Não. São necessárias informações geométricas, calibração, profundidade ou um modelo adequado e transformação entre referenciais.')

m('navegacao','Localização, SLAM e navegação','Percepção','Separe mapa, estimativa de posição, planejamento e controle.', [('C','58-60')], '''
<h2>As perguntas da navegação</h2><p>Localização responde “onde estou?”; mapeamento descreve o ambiente; planejamento escolhe como chegar ao objetivo; controle acompanha o movimento. SLAM estima posição e mapa em conjunto. Ter um mapa não significa conhecer a posição exata nele, e calcular um caminho não garante que o robô consiga executá-lo.</p>
<h2>Odometria, IMU e fusão</h2><p>Encoders estimam movimento das rodas. Para uma roda sem deslizamento, v = ωr. Deslizamento e diferenças geométricas acumulam erro de odometria. Uma IMU fornece aceleração específica e velocidade angular; estimar posição por integração exige tratar gravidade, orientação e vieses. Pequenos erros podem causar deriva crescente.</p><p>Fusão sensorial combina previsões do modelo e medições novas. Filtros de Kalman e variantes ponderam informações usando modelos de incerteza. Não são uma média simples universal de todos os sensores; medições incompatíveis ou mal calibradas precisam ser identificadas.</p>
<h2>Robô diferencial</h2><div class="formula">v = (v_direita + v_esquerda)/2<br>ω_corpo = (v_direita − v_esquerda)/b</div><p>b é a distância entre as rodas. As expressões assumem rolamento ideal e uma convenção de sinais. Rodas com a mesma velocidade avançam em linha reta; velocidades opostas permitem girar sobre o centro no modelo ideal.</p>
<div class="worked"><h3>Velocidade da roda</h3><p>Roda de raio 0,05 m a 120 rpm: ω = 120 × 2π/60 = 4π rad/s. v = 4π × 0,05 = <strong>0,628 m/s</strong>, sem deslizamento. Converter rpm diretamente para m/s sem o fator 2π/60 dá uma resposta errada.</p></div>
<h2>Planejadores citados</h2><p>Dijkstra procura caminhos de custo mínimo em grafos com custos não negativos. A* acrescenta uma heurística para orientar a busca. RRT explora o espaço por amostragem; RRT* acrescenta estratégias para melhorar custo com mais amostras sob hipóteses apropriadas. São princípios distintos, não sinônimos de desvio de obstáculos.</p>
<p>Um caminho deve considerar tamanho do robô, folga de obstáculos, raio de giro, velocidade e aceleração. Obstáculos móveis pedem atualização e resposta local.</p>''','Por que SLAM é mais do que desenhar um mapa?','Porque estima simultaneamente o mapa e a posição do próprio robô, tratando a dependência entre essas duas informações.')

m('ia','Inteligência artificial na robótica','Computação','Entenda classificação, reforço, sim-to-real e integração com controle.', [('C','61-63'),('I','42'),'dartmouth'], '''
<h2>Função antes do nome do algoritmo</h2><p>IA pode classificar objetos, detectar anomalias, prever eventos ou escolher ações. Primeiro defina entrada, saída e critério de sucesso. “O robô terá IA” não explica como ele resolve um problema. Uma tarefa pode ser feita por regra clássica, modelo probabilístico ou aprendizado, conforme suas necessidades.</p>
<h2>Aprendizado supervisionado e redes</h2><p>No supervisionado, dados com respostas conhecidas orientam o aprendizado. Para classificar frutas, imagens e rótulos treinam um modelo. Separe treino e avaliação: testar nas mesmas imagens usadas para aprender pode ocultar falhas de generalização. Mudanças de iluminação, variedade e ambiente podem reduzir a qualidade no uso real.</p>
<h2>Aprendizado por reforço</h2><p>Um agente observa um estado ou observação, escolhe uma ação, recebe uma recompensa e aprende uma política visando recompensa acumulada. Recompensa imediata e objetivo real não são sempre equivalentes. Um critério mal formulado pode incentivar velocidade com movimentos perigosos ou estratégias que exploram a simulação sem resolver a tarefa.</p>
<div class="worked"><h3>Robô que evita obstáculos</h3><p>Uma política pode receber distância ao obstáculo e posição relativa à meta e escolher velocidades. Recompensar aproximação da meta e penalizar colisões é um começo, mas ainda é necessário avaliar tempo, suavidade, limites e cenários não vistos. Uma regra de parada separada pode limitar ações inadequadas, conforme a arquitetura validada.</p></div>
<h2>Sim-to-real gap</h2><p>Simulações aproximam atrito, massas, ruído, atrasos e sensores. Uma política que funciona ali pode falhar no mundo físico. Variação de parâmetros e testes graduais ajudam a investigar robustez, mas não oferecem uma garantia automática.</p>
<h2>Integração híbrida</h2><p>Uma rede pode identificar uma peça e um controlador clássico seguir a referência resultante. A decisão da rede ainda precisa ser verificada: peça errada, pose impossível ou informação atrasada podem gerar um comando inadequado. Defina o que fazer quando não há informação confiável e quais limites não podem ser ultrapassados.</p>''','Qual é o principal risco de testar só com os dados de treinamento?','Confundir memorização ou ajuste aos exemplos conhecidos com capacidade de generalizar para situações novas.')

m('seguranca','Segurança, colaboração e confiabilidade','Aplicações','Entenda riscos, diagnósticos e limites de sistemas colaborativos.', [('C','64-66'),'seguranca'], '''
<h2>Analise o sistema inteiro</h2><p>Riscos vêm do braço, ferramenta, peça, máquinas próximas e operações de ajuste ou manutenção. Uma garra pontiaguda ou carga pesada pode tornar perigosa uma aplicação mesmo com um braço de potência limitada. O manual técnico da OSHA destaca avaliação da instalação e proteções ao longo das tarefas.</p>
<h2>Medidas citadas nas aulas</h2><ul><li>Barreiras e sensores de presença reduzem acesso a regiões perigosas.</li><li>Monitoramento de velocidade e torque limita condições de movimento conforme o projeto.</li><li>Paradas e desligamento de emergência respondem a condições previstas.</li><li>Diagnósticos, watchdog e proteção contra sobrecorrente ajudam a detectar falhas.</li><li>Redundância oferece caminhos adicionais, mas precisa tratar falhas comuns.</li></ul>
<p>Parada de emergência não substitui as proteções normais. Parar o movimento e isolar fontes de energia não são necessariamente a mesma ação; energia elétrica, pressão e gravidade podem continuar presentes.</p>
<h2>Robótica colaborativa</h2><p>Trabalhar perto de pessoas exige avaliar a aplicação concreta. Detectar contato ou limitar força é uma parte do projeto, não uma garantia universal. Avalie ferramenta, peça, pontos de esmagamento, velocidade, distância e falhas. Colaboração também pode depender de separação monitorada ou de outros métodos adequados à tarefa.</p>
<h2>Fail-safe e confiabilidade</h2><p>Fail-safe significa que falhas identificadas levam a uma condição prevista como segura. “Desligar tudo” pode ser inadequado se isso derrubar uma carga; o estado seguro precisa ser especificado. Confiabilidade trata da capacidade de cumprir a função ao longo do uso. Disponibilidade e segurança são critérios relacionados, mas distintos.</p>
<div class="worked"><h3>Perda de comunicação</h3><p>Um robô móvel deixa de receber comandos. O projeto pode detectar timeout e reduzir velocidade até uma parada controlada, mantendo recursos necessários à estabilidade. A política deve ser definida e validada para o sistema, em vez de continuar executando indefinidamente a última velocidade recebida.</p></div>
<p>Este capítulo ensina conceitos da prova e usa a OSHA como complemento técnico. Não é certificação nem avaliação normativa de uma instalação brasileira.</p>''','Um cobot é seguro em qualquer aplicação?','Não. Segurança depende do conjunto da aplicação, ferramenta, peça, movimento, ambiente e medidas verificadas.')

m('aplicacoes','Aplicações e critérios de engenharia','Aplicações','Conecte indústria, medicina, agricultura, serviços e exploração.', [('C','67-70'),('A','38'),'nasa'], '''
<h2>A mesma base, restrições diferentes</h2><p>Na indústria, manipuladores soldam, pintam, montam, inspecionam e transportam. Em medicina, robôs podem apoiar procedimentos e reabilitação, com exigências próprias de precisão, interação e supervisão. Na agricultura, iluminação, terreno, clima e variabilidade biológica mudam a percepção e a locomoção. Em serviços, compartilhar espaços com usuários torna comunicação e previsibilidade importantes.</p>
<p>A NASA apresenta usos em exploração planetária, assistência e sistemas autônomos. Comunicação limitada e ambiente desconhecido podem exigir decisões locais. Isso ajuda a explicar por que um rover não pode depender sempre de comandos humanos instantâneos.</p>
<h2>Produção e tempo de ciclo</h2><p>Uma célula deve sincronizar robô, alimentação de peças, máquinas e inspeção. A etapa mais lenta pode limitar a produção. Melhorar a velocidade do braço não aumenta a produção se a máquina seguinte permanece ocupada. Avalie gargalos e tempos de espera.</p><div class="formula">Produção ideal por hora = 3600 / tempo_de_ciclo(s)</div>
<div class="worked"><h3>Um ciclo de 12 segundos</h3><p>A produção ideal é 3600/12 = <strong>300 ciclos/h</strong>. Com fração produtiva didática de 80%, estima-se 240 ciclos/h, mantendo uma peça por ciclo. Refugos, manutenção, abastecimento e organização do processo podem reduzir ainda mais a produção útil.</p></div>
<h2>Como justificar escolhas</h2><p>Defina problema, ambiente, objeto e métrica. Para colheita, considere detectar maturação e não danificar o produto. Para logística, considere carga, piso, corredores, pessoas e autonomia. Para inspeção, descreva qual defeito é detectado e como validar a detecção. Usar uma câmera não explica sozinho a qualidade da inspeção.</p>
<h2>Custos e comparação</h2><p>Ao comparar componentes reais, inclua modelo, documentação, condições de especificação e data de consulta. Preços e disponibilidade mudam. Custos de integração, ferramentas, treinamento e manutenção podem ser relevantes além do braço. Não transforme uma comparação qualitativa de aula em orçamento confiável.</p>
<p>O principal exercício é encadear requisitos e soluções: a tarefa impõe movimentos; os movimentos pedem mecanismos; os mecanismos pedem potência e controle; o ambiente pede sensores e proteção.</p>''','Por que um robô mais rápido pode não aumentar a produção de uma célula?','Porque o gargalo pode estar em outra etapa, como alimentação de peças, máquina de processo ou inspeção.')

m('projeto','Projete um robô autônomo','Aplicações','Siga o desafio da aula com requisitos, arquitetura e dimensionamento.', [('C','71-82')], '''
<h2>Transforme uma ideia em proposta verificável</h2><p>A atividade pede um projeto virtual fundamentado, sem construção física obrigatória. A aula propõe inspeção industrial, agricultura, logística, coleta seletiva, segurança e exploração. Escolha um problema limitado: “transportar caixas de até 2 kg entre duas bancadas em piso plano” é mais verificável que “fazer um robô inteligente”.</p>
<h2>As etapas do material</h2><ol><li><strong>Definição:</strong> problema, usuário, ambiente, autonomia, movimentos, carga, precisão, velocidade e duração.</li><li><strong>Arquitetura:</strong> desenhe sensores → controlador/algoritmos → drivers → atuadores, com alimentação e comunicação.</li><li><strong>Componentes:</strong> pesquise modelos reais e documentação técnica; compare fabricante, tensão, corrente, potência, resolução, dimensões e custo datado.</li><li><strong>Dimensionamento:</strong> faça ao menos três cálculos: potência P = τω, energia E = Pt e velocidade v = ωr, com unidades e hipóteses.</li><li><strong>Controle:</strong> defina variável controlada, sensor, erro e ação corretiva; desenhe uma malha.</li><li><strong>Demonstração virtual:</strong> represente movimento, circuito, software ou estrutura com ferramenta apropriada.</li><li><strong>Função autônoma:</strong> explique um algoritmo para trajetória, obstáculos, localização, classificação ou outra função.</li></ol>
<div class="worked"><h3>Exemplo de logística, com hipóteses</h3><p>Raio de roda 0,05 m, velocidade desejada 0,5 m/s: ω = v/r = 10 rad/s ≈ 95,5 rpm. Torque hipotético de 0,4 N·m por roda: potência mecânica = 4 W por roda; duas rodas somam 8 W nesse ponto. Isso ainda não dimensiona arrancada ou subida. Se o consumo elétrico total médio estimado for 25 W durante 2 h, serão necessárias 50 Wh utilizáveis. Com fração utilizável de 80%, energia nominal mínima estimada = 62,5 Wh.</p></div>
<h2>O que entregar</h2><p>Inclua uma página de requisitos, diagrama funcional, tabela de componentes com fontes, memória de cálculo, malha de controle, função autônoma e limites conhecidos. Uma boa proposta admite incertezas e planeja como medi-las. Valores hipotéticos precisam ficar marcados como tal, e não como especificações de uma peça real.</p>
<p>Na página de atividades há um roteiro preenchível e uma rubrica de autoavaliação. O laboratório ajuda a explorar as contas, mas não substitui simulação física ou validação dos componentes.</p>''','Quais são os três cálculos mínimos do desafio?','Potência mecânica P = τω; energia E = Pt; velocidade linear de roda v = ωr, usando unidades compatíveis e hipóteses declaradas.')


# Complementos necessários para figuras, modelos e notações dos PDFs.
additions = {
 'motores': """<h2>Modelo elétrico e tipos adicionais</h2><p>A aula 03 usa V = Keω + Ri e τ = Kti: a força contraeletromotriz cresce com velocidade e o torque cresce com corrente. Esse é um modelo simplificado em regime; no transitório pode ser necessário incluir L di/dt. Motor síncrono acompanha o campo girante em operação sincronizada; no motor de indução, a produção de torque envolve escorregamento. Um atuador linear produz movimento linear, diretamente ou por mecanismos como fusos.</p><h2>Sequências do motor de passo</h2><p>A apostila representa quatro bobinas por bits. A sequência 1–2–4–8 excita uma bobina por vez; inverter para 8–4–2–1 inverte o sentido no modelo mostrado. Meio passo pode intercalar estados com uma e duas bobinas, como 1–3–2–6–4–12–8–9. Esses números representam máscaras de bits, não tensões nem a ligação de qualquer driver comercial. Consulte o diagrama do mecanismo antes de aplicar uma sequência.</p>""",
 'estrutura': """<h2>Materiais e elementos finitos</h2><p>A aula menciona aço, alumínio, polímeros técnicos e compósitos. Compare rigidez, massa, resistência, ambiente e fabricação; material mais leve não é sempre melhor. A análise por elementos finitos divide uma estrutura em partes menores e aproxima deformações e tensões. Cargas, apoios, propriedades e malha precisam representar o problema: uma imagem colorida de simulação não confirma sozinha um projeto.</p>""",
 'juntas': """<h2>Mobilidade e o modelo do braço humano</h2><p>A aula 06 compara quantidade de juntas com movimentos da tarefa usando um tripé telescópico e apresenta o braço humano como 7 GL: ombro 3, cotovelo 1 e conjunto distal 3. É uma abstração didática. Na análise de mecanismos, é preciso distinguir coordenadas internas independentes, movimentos do efetuador e juntas acopladas; não use uma contagem visual como regra universal. RRPS tem 1 + 1 + 1 + 3 = 6 GL no modelo serial sem vínculos adicionais. Transportar e girar uma peça sobre uma mesa pode pedir x, y, z e uma orientação: 4 variáveis de tarefa.</p>""",
 'workspace': """<h2>SCARA ideal: comprimentos fixos</h2><p>Para dois elos fixos L1 e L2, com rotações completas, o alcance planar varia de |L1 − L2| até L1 + L2. Com curso vertical h, V = πh[(L1 + L2)² − (L1 − L2)²] = 4πhL1L2. A expressão vale para L1 maior ou menor que L2. As páginas 24–25 da aula 06 usam uma região sem vazio quando L2 ≥ L1; esse preenchimento não decorre apenas de inverter dois comprimentos fixos. Confira as hipóteses geométricas do modelo do slide; para um 2R fixo, só L1 = L2 permite alcançar o centro idealmente.</p><p>Na comparação ideal da página 26 com comprimentos L e cursos iguais, os volumes indicados são: cartesiano L³; cilíndrico 3πL³; esférico 28πL³/3; SCARA 4πL³; articulado vertical 32πL³/3. Esses números dependem das hipóteses daquela comparação e não medem a eficiência de um robô real.</p>""",
 'programacao': """<h2>Máxima velocidade ou chegada sincronizada?</h2><p>Na comparação PTP da apostila, uma junta precisa girar 90° e outra 45°. Com ambas na mesma velocidade angular, a segunda termina primeiro. Para chegarem ao mesmo tempo em um modelo sem aceleração, a segunda gira à metade da velocidade da primeira. Sincronizar tempos pode suavizar a execução, mas não transforma automaticamente a trajetória do TCP em uma reta. Splines e curvas de Bézier são exemplos de interpolação suave citados no material.</p>""",
 'projeto': """<h2>Os dez itens de definição do slide</h2><p>Responda: problema; usuário; ambiente; principais riscos; grau de autonomia; robô móvel ou estacionário; carga; precisão; velocidade; tempo de funcionamento. A aula também inclui formação de equipe e pesquisa de componentes. Para estudar individualmente, use os mesmos itens como roteiro e deixe o número de integrantes conforme a orientação do professor.</p>""",
}
for lesson in MODULES:
 if lesson['id'] in additions: lesson['body'] += additions[lesson['id']]

for lesson in MODULES:
 if lesson['id']=='desempenho':
  lesson['refs'].append('iso9283')
  lesson['body'] += '''<h2>Por que aparecem normas de ensaio?</h2><p>A aula introdutória cita a ISO 9283:1998. Seu assunto é critérios de desempenho e métodos de ensaio para manipuladores industriais. A função didática é entender que uma especificação precisa dizer o que é medido e em quais condições, para permitir comparação. Um ensaio de repetibilidade não responde automaticamente à pergunta de exatidão absoluta, nem equivale a certificar toda a segurança da célula. A página oficial da ISO identifica o escopo; o texto normativo completo não foi reproduzido aqui.</p>'''
 if lesson['id']=='historia':
  lesson['body'] += '''<h2>Outros exemplos históricos dos slides</h2><p>O Menino Arqueiro de Tanaka Hisashige, apresentado com o marco de 1850, ilustra movimentos mecânicos sequenciados e expressividade de um autômato. O Four Legged Walking Truck, apresentado em 1968, exemplifica o problema de coordenar locomoção com vários apoios. O Milacron T³, apresentado em 1973, liga o controle de manipuladores ao uso de minicomputadores. Hannibal e Attila ilustram comportamentos inspirados em insetos, enquanto protótipos Honda P1/P2/P3, ASIMO e Qrio destacam locomoção e forma humanoide. Aibo e produtos iRobot mostram objetivos diferentes, como entretenimento e limpeza.</p><p>Use essas datas como marcos do material fornecido, sem assumir que o ano de um slide descreve todo o desenvolvimento do projeto ou a primeira ocorrência mundial de cada tecnologia. Aprenda a conexão: mecanismo programável → instruções; sensores simples → reação; computador → cálculo e planejamento; locomoção → equilíbrio e coordenação; serviços → interação com ambiente e usuários.</p>'''
